export default {
    Action: require('../assets/images/genres/Action-icon.png'),
    Adventure: require('../assets/images/genres/Adventure-icon.png'),
    Animation: require('../assets/images/genres/Animation-icon.png'),
    Comedy: require('../assets/images/genres/Comedy-icon.png'),
    Crime: require('../assets/images/genres/Crime-icon.png'),
    Documentary: require('../assets/images/genres/Documentary-icon.png'),
    Drama: require('../assets/images/genres/Drama-icon.png'),
    Family: require('../assets/images/genres/Family-icon.png'),
    Fantasy: require('../assets/images/genres/Fantasy-icon.png'),
    History: require('../assets/images/genres/History-icon.png'),
    Horror: require('../assets/images/genres/Horror-icon.png'),
    Music: require('../assets/images/genres/Music-icon.png'),
    Mystery: require('../assets/images/genres/Mystery-icon.png'),
    Romance: require('../assets/images/genres/Romance-icon.png'),
    Science_Fiction: require('../assets/images/genres/Scifi-icon.png'),
    Thriller: require('../assets/images/genres/Thriller-icon.png'),
    TV_Movie: require('../assets/images/genres/TV-movies-icon.png'),
    War: require('../assets/images/genres/War-icon.png'),
    Western: require('../assets/images/genres/Western-icon.png'),
}