export default {
    Action: require('../assets/images/Action.webp'),
    Adventure: require('../assets/images/Adventure.webp'),
    Animation: require('../assets/images/Animation.webp'),
    Comedy: require('../assets/images/Comedy.webp'),
    Crime: require('../assets/images/Crime.webp'),
    Documentary: require('../assets/images/Documentary.webp'),
    Drama: require('../assets/images/Drama.webp'),
    Family: require('../assets/images/Family.webp'),
    Fantasy: require('../assets/images/Fantasy.webp'),
    History: require('../assets/images/History.webp'),
    Horror: require('../assets/images/Horror.webp'),
    Music: require('../assets/images/Music.webp'),
    Mystery: require('../assets/images/Mystery.webp'),
    Romance: require('../assets/images/Romance.webp'),
    Science_Fiction: require('../assets/images/Science_Fiction.webp'),
    Thriller: require('../assets/images/Thriller.webp'),
    TV_Movie: require('../assets/images/TV_Movie.webp'),
    War: require('../assets/images/War.webp'),
    Western: require('../assets/images/Western.webp'),
}