export default {
    Action: require('../assets/images/Action.jpg'),
    Adventure: require('../assets/images/Adventure.jpg'),
    Animation: require('../assets/images/Animation.jpg'),
    Comedy: require('../assets/images/Comedy.jpg'),
    Crime: require('../assets/images/Crime.jpg'),
    Documentary: require('../assets/images/Documentary.jpg'),
    Drama: require('../assets/images/Drama.jpg'),
    Family: require('../assets/images/Family.jpg'),
    Fantasy: require('../assets/images/Fantasy.jpg'),
    History: require('../assets/images/History.jpg'),
    Horror: require('../assets/images/Horror.jpg'),
    Music: require('../assets/images/Music.jpg'),
    Mystery: require('../assets/images/Mystery.jpg'),
    Romance: require('../assets/images/Romance.jpg'),
    Science_Fiction: require('../assets/images/Science_Fiction.jpg'),
    Thriller: require('../assets/images/Thriller.jpg'),
    TV_Movie: require('../assets/images/TV_Movie.jpg'),
    War: require('../assets/images/War.jpg'),
    Western: require('../assets/images/Western.jpg'),
}